#!/bin/bash

# Starting to write file

echo -e "// This file was generated by bb2HRVcoeffs.sh\n" > bb2HRVcoeffs.cpp;

# Including all coefficients

echo -e '#include "bb2Hg/bb2HRVcoeffs.h"' >> bb2HRVcoeffs.cpp;
for i in $(ls coeff*.h); do echo '#include "'$i'"' >> bb2HRVcoeffs.cpp; done

# Opening function

echo -e "\ndouble bb2Hgbis(const double& s12, const double& s14, const double& s24)\n{" >> bb2HRVcoeffs.cpp
echo "    double foo = 0.;" >> bb2HRVcoeffs.cpp

# Adding diagrams
counter=0
for i in $(ls coeff*.h)
do 
    counter=$[counter+1]
    echo -n "    foo += productCoeff(bb2Hgbis<" >> bb2HRVcoeffs.cpp
    echo -n $counter >> bb2HRVcoeffs.cpp
    echo -n ">(s12,s14,s24)," >> bb2HRVcoeffs.cpp
    cat $i | grep Master | awk {'printf $5;'} >> bb2HRVcoeffs.cpp
    echo ",0);" >> bb2HRVcoeffs.cpp
done

# Closing function

echo "    return foo;" >> bb2HRVcoeffs.cpp
echo "}" >> bb2HRVcoeffs.cpp
