#!/bin/bash

# Starting to write file

echo -e "// This file was generated by allcoeffs.sh\n" > allcoeffs.cpp;

# Including all coefficients

echo -e '#include "qq2yyg/allcoeffs.h"' >> allcoeffs.cpp;
for i in $(ls coeff*.h); do echo '#include "'$i'"' >> allcoeffs.cpp; done

# Opening function

echo -e "\ndouble qq2yyg(const double& s12, const double& s13, const double& s14, const double& s23, const double& s24)\n{" >> allcoeffs.cpp
echo "    const double CAm2CF = QCD::CA-2.*QCD::CF;" >> allcoeffs.cpp
#echo "    const double (-s12-s13-s14) = -s12-s13-s14;" >> allcoeffs.cpp
#echo "    const double (-s12-s23-s24) = -s12-s23-s24;" >> allcoeffs.cpp
#echo "    const double (s12+s14+s24) = s12+s14+s24;" >> allcoeffs.cpp
#echo "    const double (s12+s13+s23) = s12+s13+s23;" >> allcoeffs.cpp
#echo "    const double (-s12-s13-s14-s23-s24) = -s12-s13-s14-s23-s24;" >> allcoeffs.cpp
echo "    double foo = 0.;" >> allcoeffs.cpp

# CA terms
counter=0
for i in $(ls coeffCA*.h | grep -v "CAm2CF")
do 
    counter=$[counter+1]
    echo -n "    foo += QCD::CA*productCoeff(qq2yygCA<" >> allcoeffs.cpp
    echo -n $counter >> allcoeffs.cpp
    echo -n ">(s12,s13,s14,s23,s24)," >> allcoeffs.cpp
    cat $i | grep Master | awk {'printf $5;'} >> allcoeffs.cpp
    echo ",0);" >> allcoeffs.cpp
done

# CF terms
counter=0
for i in $(ls coeffCF*.h)
do 
    counter=$[counter+1]
    echo -n "    foo += QCD::CF*productCoeff(qq2yygCF<" >> allcoeffs.cpp
    echo -n $counter >> allcoeffs.cpp
    echo -n ">(s12,s13,s14,s23,s24)," >> allcoeffs.cpp
    cat $i | grep Master | awk {'printf $5;'} >> allcoeffs.cpp
    echo ",0);" >> allcoeffs.cpp
done

# CAm2CF terms
counter=0
for i in $(ls coeffCAm2CF*.h)
do 
    counter=$[counter+1]
    echo -n "    foo += CAm2CF*productCoeff(qq2yygCAm2CF<" >> allcoeffs.cpp
    echo -n $counter >> allcoeffs.cpp
    echo -n ">(s12,s13,s14,s23,s24)," >> allcoeffs.cpp
    cat $i | grep Master | awk {'printf $5;'} >> allcoeffs.cpp
    echo ",0);" >> allcoeffs.cpp
done

# Closing function

echo "    return foo;" >> allcoeffs.cpp
echo "}" >> allcoeffs.cpp
